# Generated by Django 2.0 on 2018-07-19 17:22

from django.db import migrations
import pdbdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdbdb', '0002_auto_20180719_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainproperty',
            name='chain',
            field=pdbdb.models.CustomBinaryCharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='residue',
            name='chain',
            field=pdbdb.models.CustomBinaryCharField(max_length=20),
        ),
    ]
