# Generated by Django 2.0 on 2018-07-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdbdb', '0003_auto_20180719_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdbresidueset',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
