# Generated by Django 2.0 on 2018-07-19 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdbdb', '0004_pdbresidueset_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtomResidueSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('atom', models.ForeignKey(db_column='atom_id', on_delete=django.db.models.deletion.DO_NOTHING, to='pdbdb.Atom')),
                ('pdb_set', models.ForeignKey(db_column='residuesetresidue_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='atoms', to='pdbdb.ResidueSetResidue')),
            ],
        ),
        migrations.AlterField(
            model_name='pdbresidueset',
            name='residue_set',
            field=models.ForeignKey(db_column='residueset_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='residuesets', to='pdbdb.ResidueSet'),
        ),
        migrations.AlterUniqueTogether(
            name='atomresidueset',
            unique_together={('pdb_set', 'atom')},
        ),
    ]
