# Generated by Django 2.0 on 2018-07-20 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdbdb', '0005_auto_20180719_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomproperty',
            name='property',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='atoms', to='pdbdb.Property'),
        ),
        migrations.AlterField(
            model_name='chainproperty',
            name='property',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='chains', to='pdbdb.Property'),
        ),
        migrations.AlterField(
            model_name='residuesetproperty',
            name='property',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='residuesets', to='pdbdb.Property'),
        ),
    ]
