# Generated by Django 2.0 on 2018-07-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdbdb', '0006_auto_20180720_0027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pdbresidueset',
            unique_together={('pdb', 'residue_set', 'name')},
        ),
    ]
