# Generated by Django 2.0 on 2018-07-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdbdb', '0007_auto_20180720_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='atom',
            name='altLoc',
            field=models.CharField(default=' ', max_length=1),
        ),
    ]
