# Generated by Django 2.0 on 2018-07-20 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdbdb', '0008_atom_altloc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='atom',
            unique_together=set(),
        ),
    ]
