# Generated by Django 2.0 on 2018-10-27 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biodatabase',
            fields=[
                ('biodatabase_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('authority', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'biodatabase',
            },
        ),
        migrations.CreateModel(
            name='Bioentry',
            fields=[
                ('bioentry_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('accession', models.CharField(max_length=128)),
                ('identifier', models.CharField(blank=True, max_length=40, null=True)),
                ('division', models.CharField(blank=True, max_length=6, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.PositiveSmallIntegerField(default=1, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'bioentry',
            },
        ),
        migrations.CreateModel(
            name='BioentryDbxref',
            fields=[
                ('bioentry_dbxref_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.SmallIntegerField(default=1, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'bioentry_dbxref',
            },
        ),
        migrations.CreateModel(
            name='BioentryPath',
            fields=[
                ('bioentry_path_id', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'bioentry_path',
            },
        ),
        migrations.CreateModel(
            name='BioentryQualifierValue',
            fields=[
                ('bioentry_qualifiervalue_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(default=1, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'bioentry_qualifier_value',
            },
        ),
        migrations.CreateModel(
            name='BioentryReference',
            fields=[
                ('bioentry_relationship_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_pos', models.IntegerField(blank=True, null=True)),
                ('end_pos', models.IntegerField(blank=True, null=True)),
                ('rank', models.SmallIntegerField(default=1, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'bioentry_reference',
            },
        ),
        migrations.CreateModel(
            name='BioentryRelationship',
            fields=[
                ('bioentry_relationship_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField(default=1, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'bioentry_relationship',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('rank', models.SmallIntegerField(default=1, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Dbxref',
            fields=[
                ('dbxref_id', models.AutoField(primary_key=True, serialize=False)),
                ('dbname', models.CharField(max_length=40)),
                ('accession', models.CharField(max_length=128)),
                ('version', models.PositiveSmallIntegerField(default=1, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'dbxref',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_pos', models.IntegerField(blank=True, null=True)),
                ('end_pos', models.IntegerField(blank=True, null=True)),
                ('strand', models.IntegerField()),
                ('rank', models.SmallIntegerField(default=1, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('ontology_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('definition', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'ontology',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('reference_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('title', models.TextField(blank=True, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('crc', models.CharField(blank=True, max_length=32, null=True, unique=True)),
            ],
            options={
                'managed': True,
                'db_table': 'reference',
            },
        ),
        migrations.CreateModel(
            name='Seqfeature',
            fields=[
                ('seqfeature_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=64, null=True)),
                ('rank', models.PositiveSmallIntegerField(default=1, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'seqfeature',
            },
        ),
        migrations.CreateModel(
            name='SeqfeatureDbxref',
            fields=[
                ('seqfeature_dbxref_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.SmallIntegerField(default=1, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'seqfeature_dbxref',
            },
        ),
        migrations.CreateModel(
            name='SeqfeaturePath',
            fields=[
                ('seqfeature_path_id', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.PositiveIntegerField(blank=True, null=True)),
                ('object_seqfeature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='object_paths', to='biosql.Seqfeature')),
                ('subject_seqfeature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_paths', to='biosql.Seqfeature')),
            ],
            options={
                'managed': True,
                'db_table': 'seqfeature_path',
            },
        ),
        migrations.CreateModel(
            name='SeqfeatureQualifierValue',
            fields=[
                ('seqfeature_qualifiervalue_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.SmallIntegerField(default=1, null=True)),
                ('value', models.TextField()),
                ('seqfeature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qualifiers', to='biosql.Seqfeature')),
            ],
            options={
                'managed': True,
                'db_table': 'seqfeature_qualifier_value',
            },
        ),
        migrations.CreateModel(
            name='SeqfeatureRelationship',
            fields=[
                ('seqfeature_relationship_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField(default=1, null=True)),
                ('object_seqfeature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='object_relationships', to='biosql.Seqfeature')),
                ('subject_seqfeature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_relationships', to='biosql.Seqfeature')),
            ],
            options={
                'managed': True,
                'db_table': 'seqfeature_relationship',
            },
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('taxon_id', models.AutoField(primary_key=True, serialize=False)),
                ('ncbi_taxon_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('node_rank', models.CharField(blank=True, max_length=32, null=True)),
                ('genetic_code', models.PositiveIntegerField(blank=True, null=True)),
                ('mito_genetic_code', models.PositiveIntegerField(blank=True, null=True)),
                ('left_value', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('right_value', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'managed': True,
                'db_table': 'taxon',
            },
        ),
        migrations.CreateModel(
            name='TaxonName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_class', models.CharField(max_length=32)),
            ],
            options={
                'managed': True,
                'db_table': 'taxon_name',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_obsolete', models.CharField(blank=True, max_length=1, null=True)),
                ('version', models.PositiveSmallIntegerField(default=1, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'term',
            },
        ),
        migrations.CreateModel(
            name='TermDbxref',
            fields=[
                ('term_dbxref_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.SmallIntegerField(default=1, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'term_dbxref',
            },
        ),
        migrations.CreateModel(
            name='TermPath',
            fields=[
                ('term_path_id', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'term_path',
            },
        ),
        migrations.CreateModel(
            name='TermRelationship',
            fields=[
                ('term_relationship_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': True,
                'db_table': 'term_relationship',
            },
        ),
        migrations.CreateModel(
            name='TermSynonym',
            fields=[
                ('term_synonym_id', models.AutoField(primary_key=True, serialize=False)),
                ('synonym', models.CharField(max_length=255)),
            ],
            options={
                'managed': True,
                'db_table': 'term_synonym',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(default='')),
                ('version', models.CharField(blank=True, default=1, max_length=64, null=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ToolRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField()),
                ('result_url', models.CharField(blank=True, max_length=255, null=True)),
                ('result_path', models.FilePathField(allow_folders=True, null=True, path='/data/runs', recursive=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(auto_now=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='runs', to='biosql.Tool')),
            ],
        ),
        migrations.CreateModel(
            name='Biosequence',
            fields=[
                ('bioentry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seq', serialize=False, to='biosql.Bioentry')),
                ('version', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('alphabet', models.CharField(blank=True, max_length=10, null=True)),
                ('seq', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'biosequence',
            },
        ),
        migrations.CreateModel(
            name='DbxrefQualifierValue',
            fields=[
                ('dbxref', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='biosql.Dbxref')),
                ('rank', models.SmallIntegerField(default=1, null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'dbxref_qualifier_value',
            },
        ),
        migrations.CreateModel(
            name='LocationQualifierValue',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='biosql.Location')),
                ('value', models.CharField(max_length=255)),
                ('int_value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'location_qualifier_value',
            },
        ),
        migrations.CreateModel(
            name='TaxIdx',
            fields=[
                ('tax', models.OneToOneField(db_column='tax_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='keywords', serialize=False, to='biosql.Taxon')),
                ('text', models.TextField()),
            ],
            options={
                'managed': True,
                'db_table': 'tax_idx',
            },
        ),
        migrations.CreateModel(
            name='TermIdx',
            fields=[
                ('term', models.OneToOneField(db_column='term_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='keywords', serialize=False, to='biosql.Term')),
                ('text', models.TextField()),
            ],
            options={
                'managed': True,
                'db_table': 'term_idx',
            },
        ),
        migrations.CreateModel(
            name='TermRelationshipTerm',
            fields=[
                ('term_relationship', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='biosql.TermRelationship')),
            ],
            options={
                'managed': True,
                'db_table': 'term_relationship_term',
            },
        ),
        migrations.AddField(
            model_name='termsynonym',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='biosql.Term'),
        ),
        migrations.AddField(
            model_name='termrelationship',
            name='object_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='object_termrelationships', to='biosql.Term'),
        ),
        migrations.AddField(
            model_name='termrelationship',
            name='ontology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Ontology'),
        ),
        migrations.AddField(
            model_name='termrelationship',
            name='predicate_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='predicate_termrelationships', to='biosql.Term'),
        ),
        migrations.AddField(
            model_name='termrelationship',
            name='subject_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_termrelationships', to='biosql.Term'),
        ),
        migrations.AddField(
            model_name='termpath',
            name='object_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='object_termpaths', to='biosql.Term'),
        ),
        migrations.AddField(
            model_name='termpath',
            name='ontology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Ontology'),
        ),
        migrations.AddField(
            model_name='termpath',
            name='predicate_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='predicate_termpaths', to='biosql.Term'),
        ),
        migrations.AddField(
            model_name='termpath',
            name='subject_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_termpaths', to='biosql.Term'),
        ),
        migrations.AddField(
            model_name='termdbxref',
            name='dbxref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Dbxref'),
        ),
        migrations.AddField(
            model_name='termdbxref',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbxrefs', to='biosql.Term'),
        ),
        migrations.AddField(
            model_name='term',
            name='ontology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Ontology'),
        ),
        migrations.AddField(
            model_name='taxonname',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='names', to='biosql.Taxon'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='parent_taxon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='biosql.Taxon'),
        ),
        migrations.AddField(
            model_name='seqfeaturerelationship',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Term'),
        ),
        migrations.AddField(
            model_name='seqfeaturequalifiervalue',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Term'),
        ),
        migrations.AddField(
            model_name='seqfeaturepath',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Term'),
        ),
        migrations.AddField(
            model_name='seqfeaturedbxref',
            name='dbxref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Dbxref'),
        ),
        migrations.AddField(
            model_name='seqfeaturedbxref',
            name='seqfeature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dbxrefs', to='biosql.Seqfeature'),
        ),
        migrations.AddField(
            model_name='seqfeature',
            name='bioentry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='biosql.Bioentry'),
        ),
        migrations.AddField(
            model_name='seqfeature',
            name='source_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_of', to='biosql.Term'),
        ),
        migrations.AddField(
            model_name='seqfeature',
            name='type_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='features_of_type', to='biosql.Term'),
        ),
        migrations.AddField(
            model_name='reference',
            name='dbxref',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Dbxref'),
        ),
        migrations.AddField(
            model_name='location',
            name='dbxref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Dbxref'),
        ),
        migrations.AddField(
            model_name='location',
            name='seqfeature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='biosql.Seqfeature'),
        ),
        migrations.AddField(
            model_name='location',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Term'),
        ),
        migrations.AlterUniqueTogether(
            name='dbxref',
            unique_together={('accession', 'dbname', 'version')},
        ),
        migrations.AddField(
            model_name='comment',
            name='bioentry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biosql.Bioentry'),
        ),
        migrations.AddField(
            model_name='bioentryrelationship',
            name='object_bioentry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='object_bioentry_relationship', to='biosql.Bioentry'),
        ),
        migrations.AddField(
            model_name='bioentryrelationship',
            name='subject_bioentry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_bioentry_relationship', to='biosql.Bioentry'),
        ),
        migrations.AddField(
            model_name='bioentryrelationship',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Term'),
        ),
        migrations.AddField(
            model_name='bioentryreference',
            name='bioentry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biosql.Bioentry'),
        ),
        migrations.AddField(
            model_name='bioentryreference',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Reference'),
        ),
        migrations.AddField(
            model_name='bioentryqualifiervalue',
            name='bioentry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifiers', to='biosql.Bioentry'),
        ),
        migrations.AddField(
            model_name='bioentryqualifiervalue',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Term'),
        ),
        migrations.AddField(
            model_name='bioentrypath',
            name='object_bioentry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='object_bioentry_path', to='biosql.Bioentry'),
        ),
        migrations.AddField(
            model_name='bioentrypath',
            name='subject_bioentry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_bioentry_path', to='biosql.Bioentry'),
        ),
        migrations.AddField(
            model_name='bioentrypath',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Term'),
        ),
        migrations.AddField(
            model_name='bioentrydbxref',
            name='bioentry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbxrefs', to='biosql.Bioentry'),
        ),
        migrations.AddField(
            model_name='bioentrydbxref',
            name='dbxref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Dbxref'),
        ),
        migrations.AddField(
            model_name='bioentry',
            name='biodatabase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='biosql.Biodatabase'),
        ),
        migrations.AddField(
            model_name='bioentry',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Taxon'),
        ),
        migrations.AlterUniqueTogether(
            name='termsynonym',
            unique_together={('term', 'synonym')},
        ),
        migrations.AddField(
            model_name='termrelationshipterm',
            name='term',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Term'),
        ),
        migrations.AlterUniqueTogether(
            name='termrelationship',
            unique_together={('subject_term', 'predicate_term', 'object_term', 'ontology')},
        ),
        migrations.AlterUniqueTogether(
            name='termpath',
            unique_together={('subject_term', 'predicate_term', 'object_term', 'ontology', 'distance')},
        ),
        migrations.AlterUniqueTogether(
            name='termdbxref',
            unique_together={('term', 'dbxref')},
        ),
        migrations.AlterUniqueTogether(
            name='taxonname',
            unique_together={('taxon', 'name', 'name_class')},
        ),
        migrations.AlterUniqueTogether(
            name='seqfeaturerelationship',
            unique_together={('object_seqfeature', 'subject_seqfeature', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='seqfeaturequalifiervalue',
            unique_together={('seqfeature', 'term', 'rank')},
        ),
        migrations.AlterUniqueTogether(
            name='seqfeaturepath',
            unique_together={('object_seqfeature', 'subject_seqfeature', 'term', 'distance')},
        ),
        migrations.AlterUniqueTogether(
            name='seqfeaturedbxref',
            unique_together={('seqfeature', 'dbxref')},
        ),
        migrations.AlterUniqueTogether(
            name='seqfeature',
            unique_together={('bioentry', 'type_term', 'source_term', 'rank')},
        ),
        migrations.AddField(
            model_name='locationqualifiervalue',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Term'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('seqfeature', 'rank')},
        ),
        migrations.AddField(
            model_name='dbxrefqualifiervalue',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biosql.Term'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('bioentry', 'rank')},
        ),
        migrations.AlterUniqueTogether(
            name='bioentryrelationship',
            unique_together={('object_bioentry', 'subject_bioentry', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='bioentryreference',
            unique_together={('bioentry', 'reference', 'rank')},
        ),
        migrations.AlterUniqueTogether(
            name='bioentryqualifiervalue',
            unique_together={('bioentry', 'term', 'rank')},
        ),
        migrations.AlterUniqueTogether(
            name='bioentrypath',
            unique_together={('object_bioentry', 'subject_bioentry', 'term', 'distance')},
        ),
        migrations.AlterUniqueTogether(
            name='bioentrydbxref',
            unique_together={('bioentry', 'dbxref', 'rank')},
        ),
        migrations.AlterUniqueTogether(
            name='bioentry',
            unique_together={('accession', 'biodatabase', 'version'), ('identifier', 'biodatabase')},
        ),
        migrations.AlterUniqueTogether(
            name='locationqualifiervalue',
            unique_together={('location', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='dbxrefqualifiervalue',
            unique_together={('dbxref', 'term', 'rank')},
        ),
    ]
