# Generated by Django 2.0 on 2018-07-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biosql', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonname',
            options={'managed': True},
        ),
    ]
