# Generated by Django 2.0 on 2018-07-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biosql', '0002_auto_20180713_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ToolRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField()),
                ('result_url', models.CharField(blank=True, max_length=255, null=True)),
                ('result_path', models.FilePathField(allow_folders=True, null=True, path='/data/runs', recursive=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(auto_now=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='runs', to='biosql.Tool')),
            ],
        ),
        migrations.AlterModelOptions(
            name='taxonname',
            options={'managed': False},
        ),
    ]
