# Generated by Django 2.0 on 2018-07-23 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biosql', '0003_auto_20180717_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxIdx',
            fields=[
                ('tax', models.ForeignKey(db_column='tax_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='biosql.Taxon')),
                ('text', models.TextField()),
            ],
            options={
                'managed': True,
                'db_table': 'tax_idx',
            },
        ),
        migrations.CreateModel(
            name='TermIdx',
            fields=[
                ('term', models.ForeignKey(db_column='term_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='biosql.Term')),
                ('text', models.TextField()),
            ],
            options={
                'managed': True,
                'db_table': 'term_idx',
            },
        ),
    ]
