# Generated by Django 2.0 on 2018-08-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biosql', '0004_taxidx_termidx'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
