# Generated by Django 2.0 on 2018-07-23 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allele',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alt', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transcript', models.CharField(blank=True, max_length=255, null=True)),
                ('variant_type', models.CharField(max_length=255)),
                ('reported', models.IntegerField()),
                ('predicted_impact', models.CharField(blank=True, max_length=255, null=True)),
                ('aa_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('aa_pos', models.IntegerField(blank=True, null=True)),
                ('aa_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('allele_fk', models.ForeignKey(db_column='allele_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='vardb.Allele')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pos', models.IntegerField()),
                ('gene', models.CharField(blank=True, max_length=255, null=True)),
                ('gene_pos', models.IntegerField(blank=True, null=True)),
                ('contig', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_organism', models.CharField(max_length=255)),
                ('ref', models.CharField(max_length=255)),
                ('modified_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Variantannotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('prop', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variantassignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allele_fk', models.ForeignKey(db_column='allele_fk', on_delete=django.db.models.deletion.CASCADE, to='vardb.Allele')),
            ],
        ),
        migrations.CreateModel(
            name='Variantcollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_organism', models.CharField(max_length=255)),
                ('sample', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='variantcollection',
            unique_together={('ref_organism', 'sample')},
        ),
        migrations.AddField(
            model_name='variantassignment',
            name='variant_collection_fk',
            field=models.ForeignKey(db_column='variant_collection_fk', on_delete=django.db.models.deletion.CASCADE, to='vardb.Variantcollection'),
        ),
        migrations.AddField(
            model_name='variantassignment',
            name='variant_fk',
            field=models.ForeignKey(db_column='variant_fk', on_delete=django.db.models.deletion.CASCADE, to='vardb.Variant'),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='assignment_fk',
            field=models.ForeignKey(db_column='assignment_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='vardb.Variantassignment'),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('ref_organism', 'contig', 'pos', 'ref')},
        ),
        migrations.AddField(
            model_name='allele',
            name='main_effect_fk',
            field=models.ForeignKey(blank=True, db_column='main_effect_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vardb.Effect'),
        ),
        migrations.AddField(
            model_name='allele',
            name='variant_fk',
            field=models.ForeignKey(db_column='variant_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='vardb.Variant'),
        ),
        migrations.AlterUniqueTogether(
            name='variantassignment',
            unique_together={('variant_collection_fk', 'variant_fk', 'allele_fk')},
        ),
        migrations.AlterUniqueTogether(
            name='allele',
            unique_together={('variant_fk', 'alt')},
        ),
    ]
