# Generated by Django 2.2.2 on 2019-07-23 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioseq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxIdx',
            fields=[
                ('tax', models.OneToOneField(db_column='tax_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='keywords', serialize=False, to='bioseq.Taxon')),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'tax_idx',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TermIdx',
            fields=[
                ('term', models.OneToOneField(db_column='term_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='keywords', serialize=False, to='bioseq.Term')),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'term_idx',
                'managed': True,
            },
        ),
    ]
