# Generated by Django 2.0.6 on 2018-06-28 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('url', models.URLField(null=True)),
                ('authority', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('ends', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('scopus_id', models.CharField(max_length=200, null=True)),
                ('scopus_names', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('scopus_id', models.CharField(max_length=200, null=True)),
                ('scopus_names', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('arg_affiliation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pmc', 'pmc'), ('bioproject', 'bioproject'), ('nuccore', 'nuccore'), ('assembly', 'assembly'), ('genome', 'genome'), ('sra', 'sra'), ('structure', 'structure')], max_length=10)),
                ('name', models.CharField(max_length=350)),
                ('description', models.TextField(blank=True)),
                ('ncbi_tax', models.IntegerField(null=True)),
                ('deprecated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('deprecated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BioProject',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bioresources.Resource')),
                ('sample_scope', models.CharField(choices=[('monoisolate', 'monoisolate'), ('multi-species', 'multi-species'), ('environment', 'environment'), ('synthetic', 'synthetic'), ('other', 'other')], max_length=20)),
                ('material', models.CharField(choices=[('genome', 'genome'), ('metagenome', 'metagenome'), ('chromosome', 'chromosome'), ('transcriptome', 'transcriptome'), ('reagent', 'reagent'), ('proteome', 'proteome')], max_length=20)),
                ('capture', models.CharField(choices=[('whole', 'whole'), ('exome', 'exome'), ('barcode', 'barcode'), ('TargetedLocusLoci', 'TargetedLocusLoci')], max_length=200)),
            ],
            bases=('bioresources.resource',),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bioresources.Resource')),
                ('doi', models.CharField(max_length=100)),
                ('date_of_publication', models.DateField(max_length=200)),
                ('pubmed_id', models.CharField(max_length=50, null=True)),
                ('electronic_id', models.CharField(max_length=50, null=True)),
                ('scopus_id', models.CharField(max_length=50, null=True)),
                ('issn', models.CharField(max_length=50, null=True)),
            ],
            bases=('bioresources.resource',),
        ),
        migrations.AddField(
            model_name='resourcerelation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='bioresources.Resource'),
        ),
        migrations.AddField(
            model_name='resourcerelation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='bioresources.Resource'),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('type', 'name')},
        ),
        migrations.AddField(
            model_name='identity',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioresources.Person'),
        ),
        migrations.AddField(
            model_name='externalid',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioresources.Organization'),
        ),
        migrations.AddField(
            model_name='externalid',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioresources.Resource'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioresources.Person'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='organizations',
            field=models.ManyToManyField(to='bioresources.Organization'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioresources.Publication'),
        ),
    ]
