# Generated by Django 2.2.2 on 2019-07-22 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('url', models.URLField(null=True)),
                ('authority', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('ends', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioresources.Person')),
            ],
            options={
                'verbose_name_plural': 'Identities',
            },
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='bioresources.Person')),
                ('organizations', models.ManyToManyField(related_name='affiliations', to='bioresources.Organization')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='bioresources.Publication')),
            ],
            options={
                'verbose_name_plural': 'Affiliations',
            },
        ),
        migrations.CreateModel(
            name='ResourceRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('deprecated', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='bioresources.Resource')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='bioresources.Resource')),
            ],
            options={
                'verbose_name_plural': 'Resource Relations',
                'unique_together': {('source', 'target', 'deprecated')},
            },
        ),
    ]
