# Generated by Django 2.0.6 on 2018-06-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
