# Generated by Django 2.2.2 on 2019-08-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('accession', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'BlastDBs',
            },
        ),
    ]
