# Generated by Django 2.2.2 on 2019-07-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0002_affiliation_identity_resourcerelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioresources.Organization')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='bioresources.Resource')),
            ],
            options={
                'verbose_name_plural': 'ExternalId',
            },
        ),
    ]
