# Generated by Django 2.2.2 on 2019-08-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0002_blastdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='blastdb',
            name='dbtype',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
