# Generated by Django 2.2.2 on 2019-07-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0003_externalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadsArchive',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bioresources.Resource')),
                ('release_date', models.DateField(null=True)),
                ('update_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Reads Archive',
            },
            bases=('bioresources.resource',),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bioresources.Resource')),
                ('country', models.CharField(max_length=100)),
                ('subdivision', models.CharField(max_length=150)),
                ('collection_date', models.DateField(null=True)),
                ('publication_date', models.DateField(null=True)),
                ('update_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Samples',
            },
            bases=('bioresources.resource',),
        ),
    ]
