# Generated by Django 2.0 on 2018-07-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0003_auto_20180706_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='gdstype',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
