# Generated by Django 2.2.2 on 2019-08-26 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0004_job_result_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='collaborators',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'NEW'), (1, 'QUEUED'), (2, 'ERROR'), (3, 'RETRYING'), (4, 'FINISHED'), (5, 'RUNNING')], default=0),
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, 'owner'), (2, 'only_producer'), (3, 'only_use'), (4, 'other')])),
                ('info', models.TextField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaboratons', to='bioresources.Person')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaboratons', to='bioresources.Resource')),
            ],
        ),
    ]
