# Generated by Django 2.0 on 2018-07-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0004_auto_20180712_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='intraspecific_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='ncbi_org',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='species_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='update_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='index_updated',
            field=models.BooleanField(default=False),
        ),
    ]
