# Generated by Django 2.2.2 on 2019-07-24 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bioresources', '0005_resourceproperty_resourcepropertyvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('result', models.TextField(null=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'NEW'), (1, 'QUEUED'), (2, 'ERROR'), (3, 'RETRYING'), (4, 'FINISHED')], default=0)),
                ('retry', models.PositiveIntegerField(default=0)),
                ('dev_error', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job',
            },
        ),
    ]
