# Generated by Django 2.2.2 on 2019-08-26 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0005_auto_20190826_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaborations', to='bioresources.Person'),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaborations', to='bioresources.Resource'),
        ),
    ]
