# Generated by Django 2.0 on 2018-07-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biosql', '__first__'),
        ('bioresources', '0005_auto_20180713_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalid',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='bioresources.Resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='ncbi_tax',
            field=models.ForeignKey(db_column='ncbi_tax', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bioresources', to='biosql.Taxon', to_field='ncbi_taxon_id'),
        ),
    ]
