# Generated by Django 2.2.2 on 2019-08-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0006_auto_20190826_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
