# Generated by Django 2.2.2 on 2019-08-27 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0007_auto_20190826_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadPDBJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bioresources.Job')),
                ('pdb', models.TextField()),
            ],
            bases=('bioresources.job',),
        ),
        migrations.RemoveField(
            model_name='job',
            name='command',
        ),
    ]
