# Generated by Django 2.0 on 2018-07-23 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0007_auto_20180723_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bioresources.Resource')),
                ('country', models.CharField(max_length=100)),
                ('subdivision', models.CharField(max_length=150)),
                ('marker', models.CharField(max_length=50, null=True)),
                ('image_url', models.URLField(null=True)),
                ('bold_org', models.CharField(max_length=255)),
                ('collectors', models.CharField(max_length=255)),
            ],
            bases=('bioresources.resource',),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='bioresources.Person'),
        ),
    ]
