# Generated by Django 2.0 on 2018-07-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0008_auto_20180723_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='bold_org',
            field=models.CharField(max_length=255, null=True),
        ),
        # migrations.AlterUniqueTogether(
        #     name='resourcerelation',
        #     unique_together={('source', 'target', 'deprecated')},
        # ),
    ]
