# Generated by Django 2.2.2 on 2019-08-02 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0008_auto_20190802_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='bioresources.Resource'),
        ),
    ]
