# Generated by Django 2.0 on 2018-07-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0009_auto_20180724_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='collectors',
            field=models.CharField(max_length=255, null=True),
        ),
        # migrations.AlterUniqueTogether(
        #     name='resourcerelation',
        #     unique_together={('source', 'target', 'deprecated')},
        # ),
    ]
