# Generated by Django 2.2.2 on 2019-08-27 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bioresources', '0009_cmdjob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmdjob',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='loadpdbjob',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='job',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_bioresources.job_set+', to='contenttypes.ContentType'),
        ),
    ]
