# Generated by Django 2.2.2 on 2019-08-27 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0010_auto_20190827_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalid',
            name='identifier',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='LoadGenomeJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bioresources.Job')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='bioresources.Assembly')),
            ],
            options={
                'base_manager_name': 'objects',
                'abstract': False,
            },
            bases=('bioresources.job',),
        ),
    ]
