# Generated by Django 2.0 on 2018-08-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0010_auto_20180724_1522'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourcerelation',
            unique_together={('source', 'target', 'deprecated')},
        ),
    ]
