# Generated by Django 2.2.2 on 2019-08-28 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bioresources', '0012_auto_20190828_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unprocessedresource',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='resource',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_bioresources.resource_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='ncbi_tax',
            field=models.ForeignKey(blank=True, db_column='ncbi_tax', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bioresources', to='bioseq.Taxon', to_field='ncbi_taxon_id'),
        ),
    ]
