# Generated by Django 2.2.2 on 2019-08-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0012_remove_affiliation_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='organizations',
            field=models.ManyToManyField(related_name='affiliations', to='bioresources.Organization'),
        ),
    ]
