# Generated by Django 2.2.2 on 2019-08-02 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0013_affiliation_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='bioresources.Resource'),
        ),
    ]
