# Generated by Django 2.2.2 on 2019-08-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0013_auto_20190828_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='scopus_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
