# Generated by Django 2.2.2 on 2019-08-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0014_auto_20190802_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliation',
            old_name='publication',
            new_name='resource',
        ),
    ]
