# Generated by Django 2.2.2 on 2019-09-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0014_auto_20190828_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unprocessedresource',
            options={},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='polymorphic_ctype',
        ),
    ]
