# Generated by Django 2.2.2 on 2019-09-02 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bioresources', '0015_auto_20190902_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unprocessedresource',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='resource',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_bioresources.resource_set+', to='contenttypes.ContentType'),
        ),
    ]
