# Generated by Django 2.2.2 on 2019-09-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0016_auto_20190902_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='asociated',
            field=models.BooleanField(default=False),
        ),
    ]
