# Generated by Django 2.2.2 on 2019-09-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0017_publication_asociated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='asociated',
            new_name='associated',
        ),
    ]
