# Generated by Django 2.2.2 on 2019-09-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioresources', '0018_auto_20190903_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unprocessedresource',
            options={},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='polymorphic_ctype',
        ),
    ]
